packages:
  - 'packages/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - 'esbuild'
  - 'sharp'
  - 'workerd'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  workerd: true

peerDependencyRules:
  allowedVersions:
    vite-dev-rpc>vite: '^8.0.0'
    vite-plugin-inspect>vite: '^8.0.0'
    vite: '*'
    vitest: '*'
  allowAny:
    - vite
    - vitest
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: ^0.1.22
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

publicHoistPattern:
  - '*vitest*'
  - vite-node
